# Generated by Django 5.0.2 on 2024-05-07 22:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('state', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Categoria',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('ruc', models.CharField(max_length=20)),
                ('direccion', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=100, null=True)),
                ('contacto', models.CharField(blank=True, max_length=200, null=True)),
                ('state', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Cliente',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('ruc', models.CharField(max_length=20)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('logo_path', models.CharField(blank=True, max_length=400, null=True)),
                ('logo_path_cotizacion', models.CharField(blank=True, max_length=400, null=True)),
                ('state', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Empresa',
            },
        ),
        migrations.CreateModel(
            name='EstadoCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Estado', models.CharField(max_length=20)),
                ('state', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'EstadoCotizacion',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('ruc', models.CharField(max_length=20)),
                ('direccion', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=100, null=True)),
                ('contacto', models.CharField(blank=True, max_length=200, null=True)),
                ('state', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Proveedor',
            },
        ),
        migrations.CreateModel(
            name='Tipo_Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=200)),
                ('state', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Tipo_Cotizacion',
            },
        ),
        migrations.CreateModel(
            name='Umedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('state', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Umedida',
            },
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('nrocotizacion', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nombre_evento', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_cotizacion', models.DateField(blank=True, null=True)),
                ('capacidad', models.CharField(blank=True, max_length=200, null=True)),
                ('lugar', models.CharField(blank=True, max_length=100, null=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=7)),
                ('mas_sin_igv', models.BooleanField()),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('totalcompra', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('ganancia', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('state', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cotizacion.cliente')),
                ('persona_creo_cotiza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('con_que_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotizacion.empresa')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotizacion.estadocotizacion')),
                ('tipo_cotizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cotizacion.tipo_cotizacion')),
            ],
            options={
                'db_table': 'Cotizacion',
                'ordering': ['fecha_cotizacion'],
            },
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('nroorden', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('fecha_orden', models.DateField()),
                ('nrofactura', models.CharField(blank=True, max_length=8, null=True)),
                ('fecha_factura', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('tipo_facturacion', models.CharField(blank=True, max_length=8, null=True)),
                ('concepto', models.TextField(blank=True, null=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=7)),
                ('monto_con_igv', models.DecimalField(decimal_places=2, max_digits=7)),
                ('monto_sin_igv', models.DecimalField(decimal_places=2, max_digits=7)),
                ('termino_dias', models.IntegerField()),
                ('pago', models.BooleanField()),
                ('comentario', models.TextField(blank=True, null=True)),
                ('state', models.BooleanField(default=True)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cotizacion.cotizacion')),
            ],
            options={
                'db_table': 'OrdenCompra',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('costo_real', models.DecimalField(decimal_places=2, max_digits=7)),
                ('costo_ofrecido', models.DecimalField(decimal_places=2, max_digits=7)),
                ('ganancia', models.DecimalField(decimal_places=2, max_digits=7)),
                ('state', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cotizacion.categoria')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cotizacion.proveedor')),
                ('umedida', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cotizacion.umedida')),
            ],
            options={
                'db_table': 'Producto',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='DetalleCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.TextField(blank=True, max_length=500, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('preciocompra', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('cantidad', models.IntegerField()),
                ('fechas', models.IntegerField()),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('costocompra', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('state', models.BooleanField(default=True)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cotizacion.cotizacion')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cotizacion.producto')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cotizacion.proveedor')),
            ],
            options={
                'db_table': 'DetalleCotizacion',
            },
        ),
    ]
