# Generated by Django 5.0.2 on 2025-01-03 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0003_categoria_imagen_producto_codigo_barra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='se_importo',
            field=models.BooleanField(default=False),
        ),
    ]
