# Generated by Django 5.0.2 on 2025-01-03 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0004_producto_se_importo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cotizacion.proveedor'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='umedida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cotizacion.umedida'),
        ),
    ]
