# Generated by Django 5.0.2 on 2025-01-04 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0005_alter_producto_proveedor_alter_producto_umedida'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen_codigo_barras',
            field=models.ImageField(blank=True, null=True, upload_to='codigos_barras/'),
        ),
    ]
